window.TRANSFER_ENGLISH_GRAMMAR = [
  {"id":"g-provide-with","title":"provide A with B","prompt":"provide가 'A에게 B를 제공하다'라는 뜻일 때 정답 구조는 무엇인가요?","quizPrompt":"'A에게 B를 제공하다'의 올바른 provide 구조를 고르세요.","answer":"provide A with B","distractors":["provide A B","provide A to B","provide A for B"],"explanation":"사람 또는 대상을 A에 두고, 제공하는 물건이나 내용을 with 뒤에 둡니다.","example":"The school provides all its students with textbooks.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-view-as","title":"view A as B","prompt":"view가 'A를 B로 보다'라는 뜻일 때 필요한 전치사는 무엇인가요?","quizPrompt":"'A를 B로 보다'의 올바른 view 구조를 고르세요.","answer":"view A as B","distractors":["view A for B","view A to B","view A with B"],"explanation":"A를 어떤 상태나 성격의 B로 판단할 때 as를 사용합니다.","example":"Most people view smart devices as useful tools.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-allow-object-to","title":"allow A to V","prompt":"allow 뒤에 목적어가 있을 때 동사는 어떤 형태로 연결하나요?","quizPrompt":"목적어가 있는 allow의 올바른 구조를 고르세요.","answer":"allow + 목적어 + to V","distractors":["allow + 목적어 + V","allow + 목적어 + V-ing","allow + to V + 목적어"],"explanation":"목적어가 어떤 행동을 하도록 허용한다는 뜻에서는 목적어 뒤에 to부정사를 둡니다.","example":"The policy allows students to choose their courses.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-recommend-that","title":"recommend that S V원형","prompt":"recommend 뒤의 that절에서 시험에 자주 나오는 동사 형태는 무엇인가요?","quizPrompt":"권고 의미의 recommend 뒤 that절에서 올바른 동사 형태를 고르세요.","answer":"recommend that S (should) V원형","distractors":["recommend that S is V-ing","recommend that S to V","recommend that S 과거형"],"explanation":"권고·제안 의미의 recommend 뒤 that절에서는 should가 생략된 동사원형이 자주 출제됩니다.","example":"The committee recommends that the project be discussed at the next meeting.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-awaken-to","title":"awaken A to B","prompt":"awaken이 'A에게 B를 깨닫게 하다'라는 뜻일 때 어떤 전치사를 사용하나요?","quizPrompt":"'A에게 B를 깨닫게 하다'의 올바른 awaken 구조를 고르세요.","answer":"awaken A to B","distractors":["awaken A B","awaken A for B","awaken A with B"],"explanation":"사람 A가 대상 B의 중요성이나 사실을 깨닫게 된다는 구조입니다.","example":"The experience awakened us to the importance of preparation.","focus":false,"type":"grammar","initialStrength":"new","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-occur-intransitive","title":"occur는 자동사","prompt":"occur를 수동태로 만들 수 있나요?","quizPrompt":"occur의 문법적 성질에 대한 올바른 설명을 고르세요.","answer":"occur는 목적어를 직접 취하지 않는 자동사이므로 일반적인 수동태로 만들지 않습니다.","distractors":["occur는 타동사이므로 목적어를 바로 취합니다.","occur는 항상 be occurred 형태로 씁니다.","occur 뒤에는 반드시 목적격 보어가 옵니다."],"explanation":"occur는 '발생하다'라는 뜻의 자동사입니다. 목적어를 직접 취하지 않기 때문에 일반적인 수동태 구조로 만들지 않습니다.","example":"Typhoons commonly occur in coastal areas.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-join-transitive","title":"join은 타동사","prompt":"'군대에 입대하다'에서 join 뒤에 to를 넣어야 하나요?","quizPrompt":"'군대에 입대하다'를 표현하는 올바른 구조를 고르세요.","answer":"join the Army","distractors":["join to the Army","join in the Army","join at the Army"],"explanation":"join은 이 용법에서 타동사이기 때문에 불필요한 전치사를 붙이지 않습니다.","example":"He joined the Army at the age of seventeen.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-lie-recline","title":"lie - lay - lain","prompt":"'눕다'라는 뜻의 lie의 과거형과 과거분사는 무엇인가요?","quizPrompt":"'눕다'라는 뜻의 lie의 변화형을 고르세요.","answer":"lie - lay - lain","distractors":["lie - lied - lied","lay - laid - laid","lie - laid - lain"],"explanation":"'눕다'의 lie는 자동사이며 과거형은 lay, 과거분사는 lain입니다.","example":"She has lain in bed since morning.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-lie-lied","title":"lie - lied - lied","prompt":"'거짓말하다'라는 뜻의 lie의 과거형과 과거분사는 무엇인가요?","quizPrompt":"'거짓말하다'라는 뜻의 lie의 변화형을 고르세요.","answer":"lie - lied - lied","distractors":["lie - lay - lain","lay - laid - laid","lie - laid - lied"],"explanation":"'거짓말하다'의 lie는 규칙 변화하여 lied, lied가 됩니다.","example":"He lied about the result.","focus":false,"type":"grammar","initialStrength":"new","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-lay-laid","title":"lay - laid - laid","prompt":"'놓다, 눕히다'라는 뜻의 lay의 과거형과 과거분사는 무엇인가요?","quizPrompt":"'놓다, 눕히다'라는 뜻의 lay의 변화형을 고르세요.","answer":"lay - laid - laid","distractors":["lie - lay - lain","lie - lied - lied","lay - lay - lain"],"explanation":"lay는 목적어를 취하는 타동사이며 과거형과 과거분사는 모두 laid입니다.","example":"She laid the book on the table.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-visit-transitive","title":"visit은 타동사","prompt":"'장소를 방문하다'에서 visit 뒤에 to가 필요한가요?","quizPrompt":"'장소를 방문하다'의 올바른 visit 구조를 고르세요.","answer":"visit + 장소","distractors":["visit to + 장소","visit at + 장소","visit for + 장소"],"explanation":"visit은 이 용법에서 타동사이므로 visit to 장소처럼 쓰지 않습니다.","example":"Tourists visiting Port Morrison often choose local restaurants.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-participate-in","title":"participate in","prompt":"participate가 '행사나 활동에 참여하다'라는 뜻일 때 필요한 전치사는 무엇인가요?","quizPrompt":"'행사나 활동에 참여하다'의 올바른 participate 구조를 고르세요.","answer":"participate in + 행사/활동","distractors":["participate + 행사/활동","participate to + 행사/활동","participate at + 행사/활동"],"explanation":"participate는 자동사이므로 참여 대상을 연결할 때 in을 사용합니다.","example":"All new workers must participate in a safety briefing.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-get-object-to","title":"get 목적어 to V","prompt":"사역 의미의 get 뒤에서 목적어가 행동하게 할 때 동사는 어떤 형태인가요?","quizPrompt":"사역 의미의 get 구조를 고르세요.","answer":"get + 목적어 + to V","distractors":["get + 목적어 + V","get + 목적어 + V-ing","get + to V + 목적어"],"explanation":"make, have, let과 달리 get은 목적어 뒤에 to부정사를 사용합니다.","example":"I got somebody to help me.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-allow-ing","title":"allow V-ing / allow A to V","prompt":"allow 뒤에 목적어가 없고 행동 자체를 허용할 때 어떤 형태를 사용할 수 있나요?","quizPrompt":"목적어가 없을 때 행동 자체를 허용하는 allow 구조를 고르세요.","answer":"allow V-ing","distractors":["allow to V","allow V원형","allow for V-ing"],"explanation":"목적어가 있으면 allow A to V를 사용하고, 행동 자체를 허용한다고 말할 때에는 allow V-ing를 사용할 수 있습니다.","example":"She doesn't allow smoking in the house.","focus":true,"type":"grammar","initialStrength":"weak","source":"편입 영어 오답노트 · 영어 문법 오답"},
  {"id":"g-present-perfect-result","title":"현재완료의 현재 연결","prompt":"현재완료는 과거 행동만 말하나요, 아니면 현재와의 연결도 나타내나요?","quizPrompt":"현재완료에 대한 올바른 설명을 고르세요.","answer":"현재완료는 과거의 행동을 현재와 연결해서 표현합니다.","distractors":["현재완료는 현재와 무관한 과거 사실만 표현합니다.","현재완료는 항상 현재 상태가 유지됨을 100% 보장합니다.","현재완료는 미래에 일어날 일만 표현합니다."],"explanation":"문맥에 따라 결과가 현재까지 이어지는 느낌을 줄 수 있지만, 현재완료 자체가 상태의 지속을 항상 보장하는 것은 아닙니다.","example":"They have laid the files on my desk.","focus":false,"type":"grammar","initialStrength":"new","source":"편입 영어 오답노트 · 영어 문법 오답"}
];